name: Dockerfile Build

on:
  push:
    branches: [main-1.33]
  pull_request:
    branches: [main-1.33]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/docker-build-dockerfile.yaml@1.0.69
    permissions:
      contents: write
      packages: write
      checks: write
    with:
      tag-version-calculation-strategy: 'file-pattern-match'
      tag-version-pattern-type: 'dockerfile-env-kubectl'
      additional-release-branches: 'main-1.33'
      docker-platform: 'linux/amd64,linux/arm64'
      dockerfile-sub-path-linux-amd64: 'src/docker'
      dockerfile-sub-path-linux-arm64: 'src/docker'
